[workspace]
members = [
  "crates/example",
  "crates/wgsl-rs",
  "crates/wgsl-rs-macros"
]

resolver = "2"

[workspace.dependencies]
glam = "0.30.9"
naga_oil = "0.20.0"
proc-macro2 = "1.0"
quote = "1.0"
snafu = "0.8.9"
syn = { version = "2.0", features = ["full", "printing", "extra-traits"] }
