[package]
name = "wgsl-rs-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true
bench = false

[dependencies]
darling = "0.23.0"
proc-macro2.workspace = true
snafu.workspace = true
syn.workspace = true
quote.workspace = true
